project:
  type: website

website:
  title: 'amanda'
  navbar:
    left:
      - href: index.qmd
        text: Home
      - git-instructions.qmd
      - corr.qmd

format:
  html:
    theme:
      - darkly
    css: styles.css
    toc: true
